### PR TITLE
Explicit types for init and cmd args

### PR DESCRIPTION
**Pull request by changlan**
Previously we used google::protobuf::Any as the argument type for module Init functions and Command functions. Inside those functions we convert google::protobuf::Any into appropriate message types using clumsy code snippets in every function:

```
pb_error_t PMDPort::Init(const google::protobuf::Any &arg_) {
  bess::pb::PMDPortArg arg;		
  arg_.UnpackTo(&arg);
  ...
```

This PR enables those functions to use module specific argument type, while keeping modules message types separate from BESS core.

### CODE REVIEW

**Comment by changlan** [comment]
Working on the same mechanism for ports.

**Comment by sangjinhan** [comment]
Let me know whenever it's ready

**Comment by changlan** [comment]
Yep, it is finished.

**Comment by sangjinhan** [comment]
Thanks!

**Pull request merged**
