### PR TITLE
Adds a queue command to get the queue's occupancy.

### PR DESCRIPTION
**Pull request by barath**

### CODE REVIEW

**Comment by barath** [comment]
Done.

**Comment by vivi** [comment]
`Queue::GetDesc` has the same logic, maybe make `QueueCommandGetStatusResponse` contain a string instead?

**Comment by barath** [comment]
Yeah -- unfortunately I want the numbers rather than a string representation.  I thought about changing `GetDesc` but it's so simple that it seemed the extra layer of indirection wasn't worth it.

**Comment by melvinw** [comment]
Thanks! cat

**Pull request merged**
