### PR TITLE
Add testing and 32-bit support for BPF module.

### PR DESCRIPTION
**Pull request by justinemarie**
Basic testing for the BPF module.

### CODE REVIEW

**Comment by justinemarie** [comment]
This PR is ready for review. @sangjinhan

**Comment by sangjinhan** [comment]
LGTM. Did some code cleanup and pushed changes to the branch. Feel free to merge unless CI complains...

**Comment by justinemarie** [comment]
Chang, can you commit since both Sangjin and I made edits? (Sangjin went through and C++-ified BPF and made it more readable after I added tests tot it).

**Comment by changlan** [comment]
image

**Pull request merged**
