### PR TITLE
Add ansible playbook file to make setting up and compiling BESS easier.

### PR DESCRIPTION
**Pull request by justinemarie**
Now that more folks are joining the BESS research team, this file has been emailed around a bunch -- would be easiest to just put it in the repo!

### CODE REVIEW

**Comment by barath** [comment]
img_0054

**Comment by sangjinhan** [comment]
On a clean Ubuntu 16.04 machine it fails with the following error:
(ran with `ansible-playbook --ask-become-pass ansible-playbook.yml`)

screen shot 2017-01-23 at 8 01 42 pm

**Comment by justinemarie** [comment]
Output makes it look like a permissions issue, but then the previous
commands work just fine and they all require sudo as well... what machine
is this on?

**Comment by sangjinhan** [comment]
It is a fresh Ubuntu Server 64 installation running on VirtualBox. No additional packages have been installed except Ansible.

**Pull request merged**
