### PR TITLE
trie: Add tests for copy constructor and assignment operator

### PR DESCRIPTION
**Pull request by changlan**
- Add tests for copy constructor and assignment operator;
- Fix implicit assignment operator;
- Use `std::unique_ptr`.

### CODE REVIEW

**Comment by sangjinhan** [comment]
Does it have any performance implications?

**Comment by changlan** [comment]
`std::unique_ptr`'s memory footprint is same as regular pointers, and its constructor and destructor should have the same performance as manual `new` and `delete`.

**Comment by sangjinhan** [comment]
I was concerned about runtime overheads (for pointer dereference). It seems that there is none: http://stackoverflow.com/questions/22295665/how-much-is-the-overhead-of-smart-pointers-compared-to-normal-pointers-in-c

Thanks!

**Comment by sangjinhan** [comment]
jjkybd3nsaqkbdxdy4fytymi_500

**Pull request merged**
