### PR TITLE
Add VLANSplit module test

### PR DESCRIPTION
**Pull request by sirspinach**

### CODE REVIEW

**Comment by sirspinach** [comment]
Passes build with bess-build image that results from this pull request: https://travis-ci.org/sirspinach/bess/jobs/249493056#L1696

**Comment by sirspinach** [comment]
The reason python3 scapy failed in the previous comment's build is that the latest release (and the current dev build) of scapy is Python2 only. I'm going to disable vlan_split test for python3 only.

**Comment by sirspinach** [comment]
Not ready: My python3 check seems to fire off during python2 run_tests. https://travis-ci.org/NetSys/bess/jobs/249710573#L1844

**Comment by sirspinach** [comment]
Ah nvm, this is ready. With the new bess-build image it somehow works properly? https://travis-ci.org/sirspinach/bess/jobs/249712362#L1694

**Comment by justinemarie** [comment]
Thanks!
image

**Comment by p-l-** [comment]
Hi there,

FYI the current development version of scapy should now work under Python 3 (and if you notice something broken, you're welcome to submit it as a bug), so you may want to test your code under Python 3.

**Comment by shinae-woo** [comment]
@p-l- @p
Hi Pierre, Thank you for your feedback! BESS is tested under python3 as well and currently, it skips VLAN split tests in case of python3. Supporting VLAN for python3 would be really great!

**Comment by p-l-** [comment]
@shinae-woo Scapy should now work with Python 3, and its VLAN support should work the same with Python 2 and Python 3.

**Pull request merged**
