### PR TITLE
Fix ratelimit overflow

### PR DESCRIPTION
**Pull request by chris3torek**
👍 Let's have Travis build this (I've already looked at it, it looks good to me)

### CODE REVIEW

**Comment by chris3torek** [comment]
(ugh, travis won't build it because of merge conflict)

**Comment by justinemarie** [comment]
Git pull --rebase origin master?

**Comment by changlan** [comment]
I just did the rebase. Let's see how it goes.

**Comment by sangjinhan** [comment]
aac273d19c15c112de5b330315329e9a

**Pull request merged**
