### PR TITLE
Fix problems with native apps

### PR DESCRIPTION
**Pull request by apanda**
Mempool naming has changed this tries to fix that problem, and fix the build.

### CODE REVIEW

**Comment by sangjinhan** [comment]
I think the code should try from 1k to 512k, not the other way around. DPDK has a bug that a mempool name lingers even if its allocation has failed. For example if 512k alloc failed but the next trial 256k worked, then there would be both pframe0_512k and pframe0_256k, but the latter one should be used.

**Comment by apanda** [comment]
Ah, I see. Will fix.

**Comment by apanda** [comment]
Done, also it is from 16K to 512K (your code doesn't go below that).

**Comment by sangjinhan** [comment]
Applied. Thanks.

**Pull request merged**
