### PR TITLE
Add comment about ansible usage

### PR DESCRIPTION
**Pull request by justinemarie**
Add a quick comment about how to use ansible -- become-pass is needed to address the glitch Sangjin saw.

### CODE REVIEW

**Comment by justinemarie** [comment]
@sangjinhan This last commit fixes the bug you found -- pip does not require sudo and so should not use become:true; if you try to give it a password it hangs because it's never prompting for sudo...

**Comment by sangjinhan** [comment]
Let's add `sudo -H` to force pip to install packages to the global repository for all users.

**Comment by sangjinhan** [comment]
Oh what I meant was `sudo -H pip install ...`, not the entire script. (=_=)

**Comment by justinemarie** [comment]
@sangjinhan

**Comment by justinemarie** [comment]
Can someone please merge this? The undergrads will want to check this out :-)

**Comment by melvinw** [comment]
Thanks! 
catsun

**Pull request merged**
