### PR TITLE
modules/port_out: pick queue using input gate

### PR DESCRIPTION
**Pull request by melvinw**
This should resolve the old TODO.

Credit to @ddiproietto for the idea.

### CODE REVIEW

**Comment by melvinw** [comment]
Not sure whether it makes more sense to pick a default, valid value for `qid` when the input gate is out of bounds or to just drop the batch. I chose to drop, but I'm happy to change if anyone feels strongly enough in the other direction.

**Comment by sangjinhan** [comment]
The original idea (which has never been implemented though) was automatic mapping between cores (workers) <-> TX queues, plus locking if necessary. But I guess we can later add an option to control its default behavior.

Dropping packets for invalid qid sounds good to me

**Comment by sangjinhan** [comment]
Note for future reference: PortOut module is not thread-safe at the moment, as multiple workers may access the same TX queue.

**Comment by sangjinhan** [comment]
defbfb8b739a101db1d3f84e3d04c1a7

**Comment by llvilanova** [comment]
Sorry to resurrect an old issue, but I just wanted to point out that the proto file was not updated to document this (which would eventually reach the wiki).

**Pull request merged**
