### PR TITLE
Fix bugs in .travis.yml

### PR DESCRIPTION
**Pull request by changlan**
- Upload codecov report when DEBUG=1
- Run unit test

### CODE REVIEW

**Comment by justinemarie** [comment]
I'm a bit confused:  How did the repo end up in this state? Did we merge a commit that didn't pass Travis?

**Comment by justinemarie** [comment]
Also, shouldn't these commits be squashed into one?

**Comment by changlan** [comment]
Just a side note: You can squash and merge on GitHub if you really care.

**Comment by justinemarie** [comment]
Ah, cool -- I forgot that they'd added that feature. Still, what's the backstory on the bug?

**Comment by justinemarie** [comment]
I figured it out -- Barath's patch failed in all_test, but passed travis because there are multiple commands on one line. See:

justine@Justines-MacBook-Pro:/$ cd ..; `exit 2`; cd .
justine@Justines-MacBook-Pro:/$ echo $?
0

So the fix is both to add ./all_test and make it 
cd .. && ./all_test && cd . 
That way is the test fails travis will notice.

**Comment by justinemarie** [comment]
@barath -- why do we need the cd rather than doing core/all_test?

**Comment by barath** [comment]
Good catch!

As for why we need cd -- it's because we need to access tracefiles for the
tcp reconstruct unit test and those are specified with a relative path, and
the relative path that we run things from is different in different
environments.  I didn't see an easy way to specify an absolute path that
would work well both locally and in travis, so changing the PWD via cd
seemed easiest.

**Comment by justinemarie** [comment]
Ah okay, so then we can't revert to ./all_tests, but we should do the && solution?

**Comment by barath** [comment]
Sounds good.

**Comment by justinemarie** [comment]
I restarted the travis job? Looks like a passing error during apt-get update.

**Comment by barath** [comment]
img_0792

**Pull request merged**
