### PR TITLE
bessctl: allow running module tests as fakeroot

### PR DESCRIPTION
**Pull request by mukerjee**

### CODE REVIEW

**Comment by chris3torek** [comment]
The Travis failure is odd, as there is no change to bessd arguments and types.  Investigating...

**Comment by chris3torek** [comment]
I can't reproduce the Travis failure. I hate to suggest "try it again" but ... try it again? 😛

**Comment by mukerjee** [comment]
Thanks @chris3torek ! I don't know how to do a re-run for travis (or I don't have permission, maybe).

**Comment by melvinw** [comment]
re-running travis for this

**Comment by mukerjee** [comment]
closing in favor of #952

**Pull request closed without merging**
