### PR TITLE
update PMD port vlan offload, mtu, enable/disable and mac address

### PR DESCRIPTION
**Pull request by nrdmao**
These changes allow PMD ports to be configured with respect to vlan offload, mtu and enable status.
These changes also allow port configuration to be updated without having to destroy and recreate the port. This is nice to have because it allows a port to be updated without having to destroy the port_inc and port_out modules and their associated connections.

### CODE REVIEW

**Comment by nrdmao** [comment]
Are there any comments or concerns regarding this pull request?

**Comment by sangjinhan** [comment]
Apologies, I will come back to this PR in a few days. Sorry for the delay.

**Comment by sangjinhan** [comment]
Please check https://github.com/aristanetworks/bess/pull/1 for suggestions I made for this PR.

**Comment by sangjinhan** [comment]
Merged (except the last merge commit), thanks!

**Comment by sangjinhan** [comment]
a

**Pull request closed without merging**
