### PR TITLE
Fix memory alignment in Queue module

### PR DESCRIPTION
**Pull request by sangjinhan**
This PR addresses #208.

### CODE REVIEW

**Comment by justinemarie** [comment]
Can you add sanity_check.sh to the .travis.yml file so Travis will show that this actually fixes the bug?

**Comment by justinemarie** [comment]
(You will also need to add 'pip install grpcio scapy' to the travis file)

**Comment by justinemarie** [comment]
Also, woohoo! Thanks @sangjinhan and @apanda!

**Comment by sangjinhan** [comment]
@justinemarie I think you can download the PR branch to your local repository, like `git fetch origin fix_alignment` (not sure about the exact command)

**Comment by justinemarie** [comment]
I did (and it passed! yay!). I can make another PR to make sure that script gets called in Travis if you think that's better?

**Comment by justinemarie** [comment]
Obligatory cats...
image

**Pull request merged**
