### PR TITLE
Eliminate namespace from tc

### PR DESCRIPTION
**Pull request by barath**
Eliminates use of namespace.h structures for TC.

### CODE REVIEW

**Comment by sangjinhan** [comment]
Could you rebase the branch to eliminate the merge commits?

**Comment by barath** [comment]
Forgot to -- one second, will send a clean pull request.

**Comment by sangjinhan** [comment]
I think pull request will automatically 'refresh' once you do rebase..? (not 100% sure)

**Comment by barath** [comment]
It should have, but it was complaining about one commit in the middle for
some reason during the rebase, so I'll just send you a clean one.

**Pull request closed without merging**
