### PR TITLE
Do not consume Ethernet headers in loopback mode

### PR DESCRIPTION
**Pull request by sangjinhan**
In the kernel module, all received packets are passed to `eth_type_trans()`. Its side effect is that packet Ethernet headers are decapsulated; not a desired behavior for loopback mode, where one would expect all sent packets return intact.

### CODE REVIEW

**Comment by sangjinhan** [comment]
This bug caused incorrect behavior of the `port/latency` example (`Measure` module do not find a marker in packets updated by `Timestamp`, due to offset shift by 14 bytes).

**Comment by shinae-woo** [comment]
LGTM.

One quick question: When is `sn_process_rx_metadata()` supposed to return rather than zero?

**Comment by sangjinhan** [comment]
I think it used to return error values regarding some offloading features. Thank you for making it `void`.

**Comment by melvinw** [comment]
Thanks! cat

**Pull request merged**
