### PR TITLE
Upload release binaries from CI

### PR DESCRIPTION
**Pull request by changlan**
Upload the GCC 6 built binaries (as well as Python scripts) whenever a tag is made.

### CODE REVIEW

**Comment by sangjinhan** [comment]
BESS daemon is built with `g++ -march=native`, so the resulting binary will require same machines instructions from the machine on which it was built. I guess Travis usually runs on GCE with AVX2, but the binary won't run on any pre-Haswell machines...

**Comment by sangjinhan** [comment]
Perhaps in the long-term, we should support binary compatibility with Function Multi-Versioning.
https://lwn.net/Articles/691932/

**Comment by changlan** [comment]
How about building with multiple `march` for legacy architectures? How many architectures we want to support?

**Comment by sangjinhan** [comment]
SSSE3 (minimum HW requirement), AVX, and AVX2 should be sufficient I guess...?

SSSE3 was the lowest spec (Core 2 architecture) we saw in the field. I think most servers are now equipped with AVX2, but there still are lots of Sandy/IvyBridge servers our there only with AVX...

**Comment by changlan** [comment]
Done. Currently it builds for three `-march` types:
- Generic `x86_64`
- `sandybridge`
- `haswell`

**Comment by changlan** [comment]
Sure. Can I update the instruction after this PR is merged to master branch? It is easier for me to generate release binary and test dependencies.

**Comment by melvinw** [comment]
Thanks! ecqhlpw

**Pull request merged**
