### PR TITLE
modules/hash_lb: add configurable n-tuple mode

### PR DESCRIPTION
**Pull request by melvinw**

### CODE REVIEW

**Comment by melvinw** [comment]
It's backwards compatible with the old `l2,l3,l4` modes. Using `bessctl/samples/conf/samples/hash_lb.bess` as a benchmark, it is a bit slower now (33.9 Mpps vs 41.8 Mpps on my machine). I took out the specialized `Lb*` functions, but I'm happy to put them back if performance is important here.

**Comment by melvinw** [comment]
Marking not ready while I put back the 'Lb*` functions

**Comment by melvinw** [comment]
Ready to go now. Impact on `l2`, `l3` and `l4` is negligible now.

**Comment by sangjinhan** [comment]
tumblr_m140vwamm61r0bljro1_1280

**Comment by chris3torek** [comment]
(I wondered about the template specializations here too, but the only other thing I thought we could do was make this use a function pointer, and that would probably be worse/slower.)

**Comment by melvinw** [comment]
Ah, I agree-- it doesn't really buy us anything-- it just felt slightly cleaner to me.

**Pull request merged**
