### PR TITLE
Add Vector TX Support

### PR DESCRIPTION
**Pull request by kot-begemot-uk**
Add support for vector/batched TX.

RX to be done separately as it requires packet pre-allocation.

Increases packet throughput > 10 times under normal conditions, more in some cases.

Signed-off-by: Anton Ivanov <anton.ivanov@cambridgegreys.com>

### CODE REVIEW

**Comment by kot-begemot-uk** [comment]
I just pushed the second half - the RX portion.

**Comment by sangjinhan** [comment]
Sorry for this late response. Could you check https://github.com/kot-begemot-uk/bess/pull/4 ?

(also, please check the CLA agreement)

**Comment by kot-begemot-uk** [comment]
The corresponding part for User Mode Linux just went into 5.4-rc1. It already had vector paravirtual nic so I only needed to add the protocol. 

It is can now talk the bess unix domain socket protocol at similar speeds (a few Gbit).

**Comment by sangjinhan** [comment]
Thanks! 0f50AIVp99uy4k64bERW0vHJ_250

**Pull request merged**
