### PR TITLE
Adds build checks for glog and gflags and documents their requirement.

### LINKED ISSUE #49: Software dependency needs to be updated
Since we are now using gflags and glog, the following files need to be updated.

build.py: `check_essential()`
docs/install.md

### PR DESCRIPTION
**Pull request by barath**
Fix #49

### CODE REVIEW

**Comment by sangjinhan** [comment]
Do we need both *-dev and the runtime library for glog and gflags? In most cases the *-dev package alone should suffice...

**Comment by barath** [comment]
You're right -- not absolutely necessary.  I can remove it.

**Comment by barath** [comment]
Updated to remove extra packages.

**Comment by sangjinhan** [comment]
Merged, thanks!

**Pull request merged**
