### PR TITLE
Fixes call to std::abs() to address clang 4.0 warning.

### PR DESCRIPTION
**Pull request by barath**

### CODE REVIEW

**Comment by sangjinhan** [comment]
What was the error clang complained about? (underflow?)

**Comment by barath** [comment]
modules/measure.cc:83:29: error: taking the absolute value of unsigned type
'unsigned long' has no effect [-Werror,-Wabsolute-value]

**Comment by sangjinhan** [comment]
Oh I see. Might be useful to add this to `common.h`...
```
template <typename T>
T absdiff(const T &lhs, const T &rhs) {
  return lhs > rhs ? lhs - rhs : rhs - lhs;
}
```

**Comment by sangjinhan** [comment]
tumblr_m8o14n0pex1rw872io1_500

**Pull request merged**
