### PR TITLE
declare all modules as final

### PR DESCRIPTION
**Pull request by melvinw**
As pointed out by @barath , this might enable optimizations that could lead to a performance gain.

### CODE REVIEW

**Comment by barath** [comment]
Thanks for this.

**Comment by sangjinhan** [comment]
Perhaps we can do the same thing with drivers?

**Comment by barath** [comment]
Melvin and I chatted about doing the same with drivers.  I think it probably won't help (given how the virtual functions for Port are called), but we might as well because it won't hurt.

**Comment by barath** [comment]
Looking at it a bit more, it may help for pmd, so might be worth doing overall.

**Comment by sangjinhan** [comment]
img

**Pull request merged**
