### PR TITLE
Support bess daemon generated traffic class name

### PR DESCRIPTION
**Pull request by shinae-woo**
* traffic class names with prefix '!'

### CODE REVIEW

**Comment by ddiproietto** [comment]
Thanks for the fix!

I've realized that we also need to handle `:` in the later characters, as the leaf tasks include that in their name.

Do you think we should enhance the exception message to include `!` (and eventually `:`) in the regex displayed to the user?

**Comment by chris3torek** [comment]
Is this exclusive to traffic class names?  If so, should we separate them out into their own `tcname+` token type?

**Comment by shinae-woo** [comment]
@ddiproietto Well, I don't know.  '!' and ':' is not intended for being used by users.  And bess daemon uses the character to prevent conflict between user-provided names.

**Comment by shinae-woo** [comment]
@chris3torek Yes, only for traffic class name. As is, it is only for monitoring, not for creating a new name.

**Comment by ddiproietto** [comment]
@shinae-woo Ok

**Comment by chris3torek** [comment]
OK, so, we could add a `tcname+` and do:

    elif var_type in ('name+', 'tcname+'):
        regexp = 'r'^[_a-zA-Z][\w]*$' if var_type == 'name+' else r'^!?[_a-zA-Z][\w:]*$'
        val = sorted(list(set(head.split())))  # collect unique items
        ... same as before ...

(or similar but change the string passed to `cli.BindError` if you want to show that `!` and `:` are allowed).

**Comment by chris3torek** [comment]
(I'll add that I don't feel strongly about this. I think you can simplify the optional `!` using `!?` rather than `(!)?`, you'd only need the parens here if you wanted to retrieve it as a group later.)

**Comment by shinae-woo** [comment]
Added traffic_class_name as @chris3torek suggested. This PR would be a just quick fix; a better solution would be refactoring the way of creating traffic class name by daemon to prevent conflict without '!'. One simple way might be, incrementally increasing the postfix indexes (`:0, :1, :2`) as of now, and check for duplication.

**Comment by sangjinhan** [comment]
Merged, thanks!
default-4

**Pull request merged**
